### ISSUE TITLE
Could not connect to the R session on RStudio Server

### ISSUE THREAD

**Issue by rgaiacs** [Bioconductor/bioconductor_docker#51]
**Describe the bug**

After login, RStudio Server shows

![Screenshot from 2022-08-26 12-45-03](https://user-images.githubusercontent.com/1506457/186823961-8498dea8-3232-413e-a12a-c70968c87ac0.png)

**To Reproduce**

Consider the following `docker-compose.yml`:

```
version: "3.9"
services:

  dev:
    image: bioconductor/bioconductor_docker:devel
    environment:
      USERID: $UID
      PASSWORD: bioc
    ports:
      - 8787:8787
    working_dir: /home/rstudio
    volumes:
      - .:/home/rstudio
```

1. Run `docker compose up dev --build`
2. Open http://localhost:878 with your web browser
3. Login using `rstudio` and `bio` for the username and password, respectively. 

**Expected behavior**

Access the web version of the RStudio IDE.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04 (`Linux raniere 5.15.0-46-generic #49-Ubuntu SMP Thu Aug 4 18:03:25 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`)
- Docker version 20.10.17, build 100c701
- Docker Compose version v2.6.0 
- Browser: Chrome
- Browser Version: 103
